app/models/__init__.py
from .products import Product
from .reviews import Review

app/models/base_model.py
class BaseModel:
    pass

app/models/products.py
from app import db
from .base_model import BaseModel


class Product(db.Model, BaseModel):
    __tablename__ = 'products'
    id = db.Column(db.Integer, primary_key=True)
    asin = db.Column(db.String(254), unique=True)
    title = db.Column(db.Text)

    reviews = db.relationship('Review', backref='product', lazy=False, cascade='all,delete')

    @property
    def serialize(self):
        """Return object data in easily serializable format"""
        return {
            'id': self.id,
            'asin': self.asin,
            'title': self.title
        }

app/models/reviews.py
from app import db
from .base_model import BaseModel


class Review(db.Model, BaseModel):
    __tablename__ = 'reviews'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(254))
    review = db.Column(db.Text)

    product_id = db.Column(db.Integer, db.ForeignKey('products.id'), nullable=True)

    @property
    def serialize(self):
        """Return object data in easily serializable format"""
        return {
            'id': self.id,
            'title': self.title,
            'review': self.review,
        }

app/forms/__init__.py
from .review_form import ReviewForm

app/forms/review_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


class ReviewForm(FlaskForm):
    """ Review form for product """

    title = StringField('Title', validators=[
        DataRequired('Please fill this field.'),
    ])

    review = TextAreaField('review', validators=[
        DataRequired('Please fill this field.'),
    ])

    submit = SubmitField('Add review')

app/__init__.py
import logging
import os
import sys
from pathlib import Path

from dotenv import load_dotenv
from flask import Flask, Blueprint
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from flask_caching import Cache

# get env vars from `.env` file
if os.path.isfile('.env'):
    print('Environment vars is loading. file: `.env`')
    filepath = os.path.join(str(Path().cwd()), '.env')

    if load_dotenv(dotenv_path=filepath, override=True):
        print('ENV `.env` loaded')
    else:
        sys.exit('Error occurred during loading env file.')

# init app
app = Flask(__name__)

host = os.getenv('DB_HOST')
port = os.getenv('DB_PORT')
database = os.getenv('DB_NAME')
user = os.getenv('DB_USER')
password = os.getenv('DB_PASSWORD')

app.config['SQLALCHEMY_DATABASE_URI'] = f'postgresql+psycopg2://{user}:{password}@{host}:{port}/{database}'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

app.config['SECRET_KEY'] = os.getenv('SECRET_KEY')

app.config['CACHE_TYPE'] = 'redis'
app.config['CACHE_DEFAULT_TIMEOUT'] = 300

app.config['CACHE_KEY_PREFIX'] = os.getenv('CACHE_KEY_PREFIX')
app.config['CACHE_REDIS_URL'] = os.getenv('CACHE_REDIS_URL')

app.config['PER_PAGE'] = 5

db = SQLAlchemy(app)
migrate = Migrate(app, db)
cache = Cache(app)


# CLI PARSE FILES
@app.cli.command("parse")
def parse():
    from cli.parse import Parse
    p = Parse()
    p.run()


# LOGGER
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG, format="%(asctime)s | %(message)s")

# blueprints for views
main_blueprint = Blueprint('main_blueprint', __name__, url_prefix='/')
api_blueprint = Blueprint('api_blueprint', __name__, url_prefix='/api')

from . import views

app.register_blueprint(main_blueprint)
app.register_blueprint(api_blueprint)

app/views/__init__.py
from . import main, api

app/views/api.py
from flask import jsonify, request
from sqlalchemy import desc
from flask_paginate import get_page_args

from app import api_blueprint, db, cache
from app.libs.helpers import get_object_or_404
from app.models import Review, Product


@api_blueprint.route("/products/<int:product_id>", methods=['GET'])
def api_product(product_id=None):
    page, per_page, offset = get_page_args(
        page_parameter='page', per_page_parameter='per_page'
    )
    cache_key = f"products:id:{product_id},page:{page},per_page:{per_page}"
    cached_response = cache.get(cache_key)
    if not cached_response:
        product = get_object_or_404(Product, product_id == Product.id)
        total = Review.query.count()
        reviews = Review.query.filter(Review.product_id == product_id).order_by(desc(Review.id)).offset(offset).limit(per_page).all()

        cached_response = jsonify(
            product=product.serialize,
            reviews=[review.serialize for review in reviews] if reviews else [],
            page=page,
            per_page=per_page,
            total=total
        )

        cache.set(cache_key, cached_response)

    return cached_response


@api_blueprint.route("/products/<string:asin>", methods=['PUT'])
def review_add(asin=None):
    if request.method == 'PUT':

        product = Product.query.filter(Product.asin == asin).first()
        if not product:
            return jsonify(status='error', errors=[{'message': ['No such product asin found']}])

        try:
            title = request.json.get('title')
            review = request.json.get('review')
        except AttributeError:
            return jsonify(status='error', errors=[{'validation': ['Check out your JSON and headers']}])

        if not title or not review:
            return jsonify(status='error', errors=[{'validation': ['Fill title & review fields']}])

        new_review = Review()
        new_review.title = title
        new_review.review = review

        product.reviews.append(new_review)
        db.session.add(new_review)
        db.session.commit()

        # TODO :)
        cache.clear()

        return jsonify(status='success')

    return jsonify(status='error', errors=[{'message': 'Wrong request format'}])

app/views/main.py
from flask import render_template, request

from app import main_blueprint
from app.forms import ReviewForm
from app.libs.helpers import get_object_or_404
from app.models import Product


@main_blueprint.route("/")
def main_index():
    return render_template(
        'index.html',
        products=Product.query.all()
    )


@main_blueprint.route("/products/<string:asin>/review/add")
def main_add_review(asin=None):
    product = get_object_or_404(Product, asin == Product.asin)
    return render_template(
        'review_add.html',
        product=product,
        form=ReviewForm(request.form)
    )

app/templates/helpers/_formhelpers.html
{% macro render_field(field, disabled=False) %}
    <div class="">
        {{ field.label }}
        {% if field.errors %}
            <ul class="errors" style="color: red">{% for error in field.errors %}<li>{{ error }}</li>{% endfor %}</ul>
        {% endif %}
        {{ field(class_="", disabled=disabled)|safe }}
    </div>
{% endmacro %}

app/templates/index.html
{% extends 'layouts/main.html' %}

{% block body %}

    <h2>Products:</h2>

    <table>
        <thead>
            <tr>
                <th>id</th>
                <th>asin</th>
                <th>title</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
                <tr>
                    <td>{{ product.id }}</td>
                    <td>{{ product.asin }}</td>
                    <td>{{ product.title }}</td>
                    <td>
                        <a href="{{ url_for('main_blueprint.main_add_review', asin=product.asin) }}">Add Review</a>
                        <a href="{{ url_for('api_blueprint.api_product', product_id=product.id) }}">API JSON</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

app/templates/layouts/main.html
{% from "helpers/_formhelpers.html" import render_field %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Product Reviews</title>
</head>
<body>

    <header>
        <a href="{{ url_for('main_blueprint.main_index') }}">Main</a>
    </header>

    <hr />

    {% block body%}{% endblock %}
    {% block js%}{% endblock %}
</body>
</html>

app/templates/review_add.html
{% extends 'layouts/main.html' %}

{% block body %}

    <h2>Product:</h2>
    <p>
        {{ product.asin }}
        <br/>
        {{ product.title }}
    </p>

    <h2>Add Review:</h2>
    <div>
        <form method="post" action="{{ url_for('api_blueprint.review_add', asin=product.asin) }}"
              onsubmit="return onSubmitReview(event)">
            {{ form.hidden_tag() }}

            {{ render_field(form.title) }}
            {{ render_field(form.review) }}

            <div class="form-group">
                {{ form.submit() }}
            </div>
        </form>
    </div>


    <h2>Reviews:</h2>
    {% for review in product.reviews %}
        <p>
            <span>{{ review.title }}</span>
            <br />
            <span>{{ review.review }}</span>
        </p>
        <hr>
    {% endfor %}

{% endblock %}

{% block js %}
    <script>

        function createNewReview() {
            return fetch("{{ url_for('api_blueprint.review_add', asin=product.asin) }}", {
              method: 'PUT',
              headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json'
               },
              body: JSON.stringify({
                title: document.getElementById('title').value,
                review: document.getElementById('review').value,
                csrf_token: document.getElementById('csrf_token').value
              })
            }).then(response => response.json())
        }

        function onSubmitReview(e) {
            e.preventDefault()

            createNewReview()
               .then((response) => {
                   if (response.status === 'success') {
                       alert('Review added')
                       window.location.reload(false);
                   }
                   if (response.status === 'error') {
                       alert(response.errors.map( (err) => Object.keys(err).map((i)=> i+ ': ' + err[i].join(', ')).join(', ') ).join('<br />'))
                   }
                })
               .catch(error => console.error(error));

            return false
        }

    </script>

{% endblock %}